### ISSUE TITLE
Error installing StatsMakie

### ISSUE THREAD

**Issue by skanskan** [JuliaPlots/StatsMakie.jl#54]
Hello

I'm trying to install it on Julia 1.0 Windows 10 and I get errors.  I've had to do it as administrator otherwise GDAL wasn't able to create a dll library.

I've done:
]

```
add AbstractPlotting#master GLMakie#master https://github.com/JuliaPlots/StatsMakie.jl.git
```
That worked well.

```
using AbstractPlotting, GLMakie, StatsMakie
[ Info: Precompiling GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a]
ERROR: LoadError: UndefVarError: AbstractBackend not defined
Stacktrace:
 getproperty(::Module, ::Symbol) at .\sysimg.jl:13
 top-level scope at none:0
 include at .\boot.jl:317 [inlined]
 include_relative(::Module, ::String) at .\loading.jl:1044
 include(::Module, ::String) at .\sysimg.jl:29
 top-level scope at none:2
 eval at .\boot.jl:319 [inlined]
 eval(::Expr) at .\client.jl:393
 top-level scope at .\none:3
in expression starting at C:\Users\joe\.julia\packages\GLMakie\Spqgl\src\GLMakie.jl:21
ERROR: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to C:\Users\joe\.julia\compiled\v1.0\GLMakie\nfnZR.ji.
Stacktrace:
 error(::String) at .\error.jl:33
 macro expansion at .\logging.jl:311 [inlined]
 compilecache(::Base.PkgId, ::String) at .\loading.jl:1190
 macro expansion at .\logging.jl:309 [inlined]
 _require(::Base.PkgId) at .\loading.jl:947
 require(::Base.PkgId) at .\loading.jl:858
 macro expansion at .\logging.jl:309 [inlined]
 require(::Module, ::Symbol) at .\loading.jl:840
```

I've also tried Pkg.update()

**Comment by skanskan** [comment]
I've unsuccessfully tried removing the clones folder and rebuilding Makie, Statsmakie, AbstractPlotting and GLMakie all from master.

**Comment by SimonDanisch** [comment]
sorry, I got into a fight with Pkg3 and looks like I lost...the weird thing is, it's really hard to reproduce this locally. I will give it another try!

**Comment by SimonDanisch** [comment]
Ok, not sure what's going on, but if I start completely from scratch, everything just works as expected:
https://nextjournal.com/sdanisch/makie-pkg3
So this must be some problem with your local pkg configuration.
Maybe just try it again! I did push a few fixes, but I'd thought I pushed them after the complaints

**Comment by SimonDanisch** [comment]
Sorry, didn't realize this is mainly about StatsMakie, but still it seems to work:
https://nextjournal.com/sdanisch/makie-pkg3

**Comment by skanskan** [comment]
@SimonDanisch 
I'm on Windows 10.
Should I find a way to install all these lines on Windows?

```
apt-get update
apt-get upgrade -y
apt-get install build-essential -y
apt-get install -y cmake mesa-utils
apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev mesa-utils
apt-get install -y ffmpeg
```

**Comment by skanskan** [comment]
I don't know what happens but I'm still getting this error:
`ERROR: LoadError: UndefVarError: AbstractBackend not defined`

**Comment by SimonDanisch** [comment]
then checking out AbstractPlotting must have failed! you dont need those on windows!

**Comment by piever** [comment]
Closing as there doesn't seem to be anything actionable on the StatsMakie side
